resolver: lts-12.12

packages:
  - .

extra-deps:
  - type-aligned-0.9.6
  - git: https://github.com/robrix/higher-order-effects
    commit: 9426ca363e8bccfc7477de13d90fcdb07b11c012
  - git: https://github.com/joshvera/effects
    commit: fc7fc0e2896239a1fef3dbc40a76c131c42e0396
